using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using SimulationPlatform.Infrastructure.Persistence;

namespace Tests.Integration;

public sealed class AdmissionDiscoveryAcceptanceTests : IClassFixture<ClassroomDatabase>
{
    private readonly ClassroomDatabase database;
    public AdmissionDiscoveryAcceptanceTests(ClassroomDatabase database) => this.database = database;
    private static HttpClient Client(DiscoveryApiFactory f, Guid id, string role) { var c = f.CreateClient(); c.DefaultRequestHeaders.Add("X-Test-User", id.ToString()); c.DefaultRequestHeaders.Add("X-Test-Role", role); return c; }
    private async Task<(ClassroomScope scope, WorkflowIds ids, Guid classroom)> Setup() { var scope = await database.CreateScope(); var ids = await scope.BuildStartedSession(); var classroom = await scope.Platform.Sessions.Where(x => x.Id == ids.Session).Select(x => x.ClassroomId).SingleAsync(); return (scope, ids, classroom); }
    private static async Task<string> Code(HttpClient c, string route) => (await (await c.GetAsync(route)).Content.ReadFromJsonAsync<JsonElement>()).GetProperty("joinCode").GetString()!;

    [Fact] public async Task Student_CanDiscoverOwnPendingClassroomRequest() { var s = await Setup(); await using var db = s.scope; using var f = new DiscoveryApiFactory(database.ConnectionString); var i = Client(f, s.ids.Instructor, "Instructor"); var code = await Code(i, $"/api/v1/classrooms/{s.classroom}/join-code"); var student = Client(f, Guid.NewGuid(), "Student"); var created = await student.PostAsJsonAsync("/api/v1/classroom-join-requests", new { code }); var id = (await created.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("requestId").GetGuid(); var response = await student.GetFromJsonAsync<JsonElement>("/api/v1/classroom-join-requests/mine"); Assert.Contains(response.EnumerateArray(), x => x.GetProperty("requestId").GetGuid() == id && x.GetProperty("status").GetString() == "Pending" && !x.TryGetProperty("joinCode", out _)); }
    [Fact] public async Task Student_CanDiscoverApprovedClassroomRequestAndMembership() { var s = await Setup(); await using var db = s.scope; using var f = new DiscoveryApiFactory(database.ConnectionString); var i = Client(f, s.ids.Instructor, "Instructor"); var code = await Code(i, $"/api/v1/classrooms/{s.classroom}/join-code"); var studentId = Guid.NewGuid(); var student = Client(f, studentId, "Student"); var created = await student.PostAsJsonAsync("/api/v1/classroom-join-requests", new { code }); var id = (await created.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("requestId").GetGuid(); Assert.Equal(HttpStatusCode.OK, (await i.PostAsJsonAsync($"/api/v1/classrooms/{s.classroom}/join-requests/{id}/approve", new { })).StatusCode); var requests = await student.GetFromJsonAsync<JsonElement>("/api/v1/classroom-join-requests/mine"); Assert.Equal("Approved", requests.EnumerateArray().Single(x => x.GetProperty("requestId").GetGuid() == id).GetProperty("status").GetString()); var memberships = await student.GetFromJsonAsync<JsonElement>("/api/v1/me/classrooms"); Assert.Contains(memberships.EnumerateArray(), x => x.GetProperty("classroomId").GetGuid() == s.classroom); }
    [Fact] public async Task ClassroomRequestDiscovery_IsolatedAndAnonymousBlocked() { var s = await Setup(); await using var db = s.scope; using var f = new DiscoveryApiFactory(database.ConnectionString); var i = Client(f, s.ids.Instructor, "Instructor"); var code = await Code(i, $"/api/v1/classrooms/{s.classroom}/join-code"); var a = Client(f, Guid.NewGuid(), "Student"); var b = Client(f, Guid.NewGuid(), "Student"); await a.PostAsJsonAsync("/api/v1/classroom-join-requests", new { code }); var bResponse = await b.GetFromJsonAsync<JsonElement>("/api/v1/classroom-join-requests/mine"); Assert.Empty(bResponse.EnumerateArray()); using var anonymous = f.CreateClient(); Assert.True((int)(await anonymous.GetAsync("/api/v1/classroom-join-requests/mine")).StatusCode >= 400); }
    [Fact] public async Task Student_CanDiscoverPendingSessionRequestWithoutPrivateData() { var s = await Setup(); await using var db = s.scope; using var f = new DiscoveryApiFactory(database.ConnectionString); var i = Client(f, s.ids.Instructor, "Instructor"); var classroomCode = await Code(i, $"/api/v1/classrooms/{s.classroom}/join-code"); var studentId = Guid.NewGuid(); var student = Client(f, studentId, "Student"); await student.PostAsJsonAsync("/api/v1/classroom-join-requests", new { code = classroomCode }); var rid = (await (await student.GetAsync("/api/v1/classroom-join-requests/mine")).Content.ReadFromJsonAsync<JsonElement>()).EnumerateArray().First().GetProperty("requestId").GetGuid(); await i.PostAsJsonAsync($"/api/v1/classrooms/{s.classroom}/join-requests/{rid}/approve", new { }); var sessionCode = await Code(i, $"/api/v1/sessions/{s.ids.Session}/join-code"); await student.PostAsJsonAsync("/api/v1/session-join-requests", new { code = sessionCode }); var response = await student.GetFromJsonAsync<JsonElement>("/api/v1/session-join-requests/mine"); var item = response.EnumerateArray().Single(); Assert.Equal("Pending", item.GetProperty("status").GetString()); Assert.False(item.TryGetProperty("role", out _)); Assert.False(item.TryGetProperty("joinCode", out _)); Assert.Equal(s.ids.Session, item.GetProperty("sessionId").GetGuid()); }
    [Fact] public async Task SessionRequestDiscovery_IsolatedAndAnonymousBlocked() { var s = await Setup(); await using var db = s.scope; using var f = new DiscoveryApiFactory(database.ConnectionString); var a = Client(f, Guid.NewGuid(), "Student"); var b = Client(f, Guid.NewGuid(), "Student"); var aResponse = await a.GetFromJsonAsync<JsonElement>("/api/v1/session-join-requests/mine"); var bResponse = await b.GetFromJsonAsync<JsonElement>("/api/v1/session-join-requests/mine"); Assert.Empty(aResponse.EnumerateArray()); Assert.Empty(bResponse.EnumerateArray()); using var anonymous = f.CreateClient(); Assert.True((int)(await anonymous.GetAsync("/api/v1/session-join-requests/mine")).StatusCode >= 400); }
}
