using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;

namespace Tests.Integration;

public sealed class ClassroomAdmissionClosureTests : IClassFixture<ClassroomDatabase>
{
    private readonly ClassroomDatabase database;
    public ClassroomAdmissionClosureTests(ClassroomDatabase database) => this.database = database;
    private static HttpClient C(DiscoveryApiFactory f, Guid u, string r){var c=f.CreateClient();c.DefaultRequestHeaders.Add("X-Test-User",u.ToString());c.DefaultRequestHeaders.Add("X-Test-Role",r);return c;}
    private async Task<(ClassroomScope s,WorkflowIds i,Guid classroom,Guid request,string code)> Setup(){var s=await database.CreateScope();var i=await s.BuildStartedSession();var classroom=await s.Platform.Sessions.Where(x=>x.Id==i.Session).Select(x=>x.ClassroomId).SingleAsync();using var f=new DiscoveryApiFactory(database.ConnectionString);var ins=C(f,i.Instructor,"Instructor");var rot=await ins.PostAsJsonAsync($"/api/v1/classrooms/{classroom}/join-code/rotate",new{});var code=(await rot.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("joinCode").GetString()!;var student=C(f,Guid.NewGuid(),"Student");var req=await student.PostAsJsonAsync("/api/v1/classroom-join-requests",new{code});var id=(await req.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("requestId").GetGuid();return(s,i,classroom,id,code);}
    [Fact] public async Task Reject_Retry_DoesNotDuplicateStateOrSideEffects(){var x=await Setup();await using var s=x.s;using var f=new DiscoveryApiFactory(database.ConnectionString);var c=C(f,x.i.Instructor,"Instructor");await c.PostAsJsonAsync($"/api/v1/classrooms/{x.classroom}/join-requests/{x.request}/reject",new{});var retry=await c.PostAsJsonAsync($"/api/v1/classrooms/{x.classroom}/join-requests/{x.request}/reject",new{});Assert.NotEqual(HttpStatusCode.InternalServerError,retry.StatusCode);Assert.Equal("Rejected",(await s.Platform.ClassroomJoinRequests.SingleAsync(q=>q.Id==x.request)).Status);Assert.Equal(1,await s.Platform.AuditRecords.CountAsync(q=>q.ResourceId==x.request.ToString()&&q.Action=="ClassroomJoinRejected"));}
    [Fact] public async Task ConcurrentJoinRequests_CreateExactlyOnePendingRequest(){var x=await Setup();await using var s=x.s;using var f=new DiscoveryApiFactory(database.ConnectionString);var studentId=Guid.NewGuid();var a=C(f,studentId,"Student");var b=C(f,studentId,"Student");var rs=await Task.WhenAll(a.PostAsJsonAsync("/api/v1/classroom-join-requests",new{code=x.code}),b.PostAsJsonAsync("/api/v1/classroom-join-requests",new{code=x.code}));Assert.DoesNotContain(rs,r=>r.StatusCode==HttpStatusCode.InternalServerError);Assert.Equal(1,await s.Platform.ClassroomJoinRequests.CountAsync(q=>q.ClassroomId==x.classroom&&q.StudentUserId==studentId&&q.Status=="Pending"));Assert.False(await s.Platform.Enrollments.AnyAsync(q=>q.ClassroomId==x.classroom&&q.UserId==studentId));}
    [Fact] public async Task ClassroomRequestMismatch_CannotApproveOrReject(){var x=await Setup();await using var s=x.s;var otherClassroom=Guid.NewGuid();using var f=new DiscoveryApiFactory(database.ConnectionString);var c=C(f,x.i.Instructor,"Instructor");var approve=await c.PostAsJsonAsync($"/api/v1/classrooms/{otherClassroom}/join-requests/{x.request}/approve",new{});var reject=await c.PostAsJsonAsync($"/api/v1/classrooms/{otherClassroom}/join-requests/{x.request}/reject",new{});Assert.True((int)approve.StatusCode>=400);Assert.True((int)reject.StatusCode>=400);Assert.Equal("Pending",(await s.Platform.ClassroomJoinRequests.SingleAsync(q=>q.Id==x.request)).Status);Assert.False(await s.Platform.Enrollments.AnyAsync(q=>q.ClassroomId==x.classroom&&q.UserId==Guid.Empty));}
}
