using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;

namespace Tests.Integration;

public sealed class ClassroomAdmissionBatch3Tests : IClassFixture<ClassroomDatabase>
{
    private readonly ClassroomDatabase database;
    public ClassroomAdmissionBatch3Tests(ClassroomDatabase database) => this.database = database;
    private static HttpClient C(DiscoveryApiFactory f, Guid u, string r) { var c=f.CreateClient(); c.DefaultRequestHeaders.Add("X-Test-User",u.ToString()); c.DefaultRequestHeaders.Add("X-Test-Role",r); return c; }
    private async Task<(ClassroomScope s, WorkflowIds i, Guid classroom, Guid request)> SetupRequest()
    {
        var s=await database.CreateScope(); var i=await s.BuildStartedSession(); var classroom=await s.Platform.Sessions.Where(x=>x.Id==i.Session).Select(x=>x.ClassroomId).SingleAsync(); using var f=new DiscoveryApiFactory(database.ConnectionString); var ins=C(f,i.Instructor,"Instructor"); var rot=await ins.PostAsJsonAsync($"/api/v1/classrooms/{classroom}/join-code/rotate",new{}); var code=(await rot.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("joinCode").GetString(); var student=C(f,Guid.NewGuid(),"Student"); var req=await student.PostAsJsonAsync("/api/v1/classroom-join-requests",new{code}); var id=(await req.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("requestId").GetGuid(); return(s,i,classroom,id);
    }
    [Fact] public async Task Instructor_Rejection_DoesNotCreateEnrollment(){var x=await SetupRequest();await using var s=x.s;using var f=new DiscoveryApiFactory(database.ConnectionString);var request=await s.Platform.ClassroomJoinRequests.AsNoTracking().SingleAsync(q=>q.Id==x.request);var r=await C(f,x.i.Instructor,"Instructor").PostAsJsonAsync($"/api/v1/classrooms/{x.classroom}/join-requests/{x.request}/reject",new{});Assert.Equal(HttpStatusCode.OK,r.StatusCode);Assert.Equal("Rejected",(await s.Platform.ClassroomJoinRequests.SingleAsync(q=>q.Id==x.request)).Status);Assert.Empty(await s.Platform.Enrollments.Where(q=>q.ClassroomId==x.classroom&&q.UserId==request.StudentUserId).ToListAsync());Assert.Equal(1,await s.Platform.AuditRecords.CountAsync(q=>q.ResourceId==x.request.ToString()&&q.Action=="ClassroomJoinRejected"));}
    [Fact] public async Task Approve_AfterRejection_DoesNotChangeTerminalState(){var x=await SetupRequest();await using var s=x.s;using var f=new DiscoveryApiFactory(database.ConnectionString);var request=await s.Platform.ClassroomJoinRequests.AsNoTracking().SingleAsync(q=>q.Id==x.request);var c=C(f,x.i.Instructor,"Instructor");await c.PostAsJsonAsync($"/api/v1/classrooms/{x.classroom}/join-requests/{x.request}/reject",new{});var r=await c.PostAsJsonAsync($"/api/v1/classrooms/{x.classroom}/join-requests/{x.request}/approve",new{});Assert.Equal(HttpStatusCode.OK,r.StatusCode);Assert.Equal("Rejected",(await s.Platform.ClassroomJoinRequests.SingleAsync(q=>q.Id==x.request)).Status);Assert.Empty(await s.Platform.Enrollments.Where(q=>q.ClassroomId==x.classroom&&q.UserId==request.StudentUserId).ToListAsync());}
    [Fact] public async Task Reject_AfterApproval_DoesNotChangeTerminalState(){var x=await SetupRequest();await using var s=x.s;using var f=new DiscoveryApiFactory(database.ConnectionString);var request=await s.Platform.ClassroomJoinRequests.AsNoTracking().SingleAsync(q=>q.Id==x.request);var c=C(f,x.i.Instructor,"Instructor");await c.PostAsJsonAsync($"/api/v1/classrooms/{x.classroom}/join-requests/{x.request}/approve",new{});var r=await c.PostAsJsonAsync($"/api/v1/classrooms/{x.classroom}/join-requests/{x.request}/reject",new{});Assert.Equal(HttpStatusCode.OK,r.StatusCode);Assert.Equal("Approved",(await s.Platform.ClassroomJoinRequests.SingleAsync(q=>q.Id==x.request)).Status);Assert.Single(await s.Platform.Enrollments.Where(q=>q.ClassroomId==x.classroom&&q.UserId==request.StudentUserId).ToListAsync());}
    [Fact] public async Task CrossInstructor_AndStudent_CannotApproveOrReject(){var x=await SetupRequest();await using var s=x.s;using var f=new DiscoveryApiFactory(database.ConnectionString);var other=C(f,x.i.OtherInstructor,"Instructor");Assert.True((int)(await other.PostAsJsonAsync($"/api/v1/classrooms/{x.classroom}/join-requests/{x.request}/approve",new{})).StatusCode>=400);var student=C(f,Guid.NewGuid(),"Student");Assert.Equal(HttpStatusCode.Forbidden,(await student.PostAsJsonAsync($"/api/v1/classrooms/{x.classroom}/join-requests/{x.request}/reject",new{})).StatusCode);Assert.Equal("Pending",(await s.Platform.ClassroomJoinRequests.SingleAsync(q=>q.Id==x.request)).Status);}
    [Fact] public async Task ConcurrentApproval_CreatesOneEnrollment(){var x=await SetupRequest();await using var s=x.s;using var f=new DiscoveryApiFactory(database.ConnectionString);var request=await s.Platform.ClassroomJoinRequests.AsNoTracking().SingleAsync(q=>q.Id==x.request);var c1=C(f,x.i.Instructor,"Instructor");var c2=C(f,x.i.Instructor,"Instructor");var rs=await Task.WhenAll(c1.PostAsJsonAsync($"/api/v1/classrooms/{x.classroom}/join-requests/{x.request}/approve",new{}),c2.PostAsJsonAsync($"/api/v1/classrooms/{x.classroom}/join-requests/{x.request}/approve",new{}));Assert.DoesNotContain(rs,r=>r.StatusCode==HttpStatusCode.InternalServerError);Assert.Equal("Approved",(await s.Platform.ClassroomJoinRequests.SingleAsync(q=>q.Id==x.request)).Status);Assert.Single(await s.Platform.Enrollments.Where(q=>q.ClassroomId==x.classroom&&q.UserId==request.StudentUserId).ToListAsync());}
    [Fact] public async Task ApproveAndReject_Concurrent_ProducesOneTerminalOutcome(){var x=await SetupRequest();await using var s=x.s;using var f=new DiscoveryApiFactory(database.ConnectionString);var request=await s.Platform.ClassroomJoinRequests.AsNoTracking().SingleAsync(q=>q.Id==x.request);var c1=C(f,x.i.Instructor,"Instructor");var c2=C(f,x.i.Instructor,"Instructor");var rs=await Task.WhenAll(c1.PostAsJsonAsync($"/api/v1/classrooms/{x.classroom}/join-requests/{x.request}/approve",new{}),c2.PostAsJsonAsync($"/api/v1/classrooms/{x.classroom}/join-requests/{x.request}/reject",new{}));Assert.DoesNotContain(rs,r=>r.StatusCode==HttpStatusCode.InternalServerError);var q=await s.Platform.ClassroomJoinRequests.SingleAsync(z=>z.Id==x.request);Assert.True(q.Status is "Approved" or "Rejected");Assert.Equal(q.Status=="Approved",await s.Platform.Enrollments.AnyAsync(z=>z.ClassroomId==x.classroom&&z.UserId==request.StudentUserId));}
}
