using System.Security.Claims;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using SimulationPlatform.Domain.Common;
using SimulationPlatform.Identity.Authorization;
using SimulationPlatform.Infrastructure.Persistence;
using SimulationPlatform.Simulations.Core.Authoring;
using SimulationPlatform.Application.Rules;
using SimulationPlatform.Application.Abstractions;
using SimulationPlatform.Application.Classrooms;
using SimulationPlatform.Simulations.Economics.Macroeconomics;
using SimulationPlatform.Simulations.Economics.CompetitiveMarket;
using SimulationPlatform.Simulations.Economics.Authoring;

namespace SimulationPlatform.Api;

public static class ScenarioProposalEndpoints
{
    public static void MapScenarioProposals(this WebApplication app)
    {
        app.MapPost("/api/v1/scenario-proposals", async (ScenarioBlueprint blueprint, ClaimsPrincipal user, PlatformDbContext db, ScenarioBlueprintValidator validator, IClock clock, HttpContext http, CancellationToken ct) =>
        {
            var owner=Id(user); var report=validator.Validate(blueprint); if(report.Blockers.Any(x=>x.Code is "scenario_blueprint.invalid_schema" or "scenario_blueprint.unsupported_model")) return Results.UnprocessableEntity(report);
            var now=clock.UtcNow; var json=JsonSerializer.Serialize(blueprint); var row=new ScenarioProposalRow{Id=Guid.NewGuid(),OwnerInstructorUserId=owner,ModelIdentifier=blueprint.ModelIdentifier,ModelVersion=blueprint.ModelVersion,SchemaVersion=blueprint.SchemaVersion,Title=blueprint.Title,Status="Draft",CurrentRevisionNumber=1,CurrentBlueprintJson=json,CreatedAt=now,UpdatedAt=now,Version=1}; db.ScenarioProposals.Add(row); db.ScenarioProposalRevisions.Add(new ScenarioProposalRevisionRow{Id=Guid.NewGuid(),ProposalId=row.Id,RevisionNumber=1,BlueprintJson=json,RevisionSource="LocalAiGeneration",CreatedByUserId=owner,CreatedAt=now}); db.AuditRecords.Add(AuditFactory.Create(owner,"ScenarioProposalCreated","ScenarioProposal",row.Id.ToString(),http.TraceIdentifier,now)); await db.SaveChangesAsync(ct); return Results.Created($"/api/v1/scenario-proposals/{row.Id}", new{row.Id,row.Status,row.Version,row.CurrentRevisionNumber});
        }).RequireAuthorization(PlatformPolicies.Instructor);
        app.MapGet("/api/v1/scenario-proposals/{id:guid}", async (Guid id, ClaimsPrincipal user, PlatformDbContext db, CancellationToken ct) => { var row=await db.ScenarioProposals.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&x.OwnerInstructorUserId==Id(user),ct); return row is null?Results.NotFound():Results.Ok(new{id=row.Id,row.ModelIdentifier,row.ModelVersion,row.SchemaVersion,row.Status,row.Version,row.CurrentRevisionNumber,blueprint=JsonSerializer.Deserialize<JsonElement>(row.CurrentBlueprintJson),row.LinkedDraftId,row.CreatedAt,row.UpdatedAt}); }).RequireAuthorization(PlatformPolicies.Instructor);
        app.MapPut("/api/v1/scenario-proposals/{id:guid}", async (Guid id, ScenarioProposalUpdate request, ClaimsPrincipal user, PlatformDbContext db, IClock clock, HttpContext http, CancellationToken ct) => { var owner=Id(user); var row=await db.ScenarioProposals.SingleOrDefaultAsync(x=>x.Id==id&&x.OwnerInstructorUserId==owner,ct)??throw new DomainException("scenario_proposal.not_found","Proposal was not found."); if(row.Status is "Rejected" or "ConvertedToScenario")throw new DomainException("scenario_proposal.immutable","Proposal is immutable."); if(row.Version!=request.ExpectedVersion)throw new DomainException("scenario_proposal.version_conflict","Proposal changed; reload and retry."); var json=JsonSerializer.Serialize(request.Blueprint); row.CurrentBlueprintJson=json;row.CurrentRevisionNumber++;row.Status="Draft";row.Version++;row.UpdatedAt=clock.UtcNow;db.ScenarioProposalRevisions.Add(new ScenarioProposalRevisionRow{Id=Guid.NewGuid(),ProposalId=row.Id,RevisionNumber=row.CurrentRevisionNumber,BlueprintJson=json,RevisionSource=request.RevisionSource??"ProfessorEdit",Instruction=request.Instruction,CreatedByUserId=owner,CreatedAt=clock.UtcNow});db.AuditRecords.Add(AuditFactory.Create(owner,"ScenarioProposalRevised","ScenarioProposal",id.ToString(),http.TraceIdentifier,clock.UtcNow));await db.SaveChangesAsync(ct);return Results.Ok(new{id=row.Id,row.Status,row.Version,row.CurrentRevisionNumber}); }).RequireAuthorization(PlatformPolicies.Instructor);
        app.MapGet("/api/v1/scenario-proposals/{id:guid}/revisions", async (Guid id, ClaimsPrincipal user, PlatformDbContext db, CancellationToken ct) => { var owner=Id(user); if(!await db.ScenarioProposals.AnyAsync(x=>x.Id==id&&x.OwnerInstructorUserId==owner,ct))return Results.NotFound(); return Results.Ok(await db.ScenarioProposalRevisions.AsNoTracking().Where(x=>x.ProposalId==id).OrderByDescending(x=>x.RevisionNumber).Select(x=>new{x.RevisionNumber,x.RevisionSource,x.Instruction,x.CreatedAt,x.CreatedByUserId}).ToListAsync(ct)); }).RequireAuthorization(PlatformPolicies.Instructor);
        app.MapGet("/api/v1/scenario-proposals/{id:guid}/revisions/{revision:int}", async (Guid id,int revision,ClaimsPrincipal user,PlatformDbContext db,CancellationToken ct)=>{var owner=Id(user);var row=await db.ScenarioProposalRevisions.AsNoTracking().Join(db.ScenarioProposals,r=>r.ProposalId,p=>p.Id,(r,p)=>new{r,p}).SingleOrDefaultAsync(x=>x.r.ProposalId==id&&x.r.RevisionNumber==revision&&x.p.OwnerInstructorUserId==owner,ct);return row is null?Results.NotFound():Results.Ok(new{row.r.RevisionNumber,blueprint=JsonSerializer.Deserialize<JsonElement>(row.r.BlueprintJson),row.r.RevisionSource,row.r.Instruction,row.r.CreatedAt,row.r.CreatedByUserId});}).RequireAuthorization(PlatformPolicies.Instructor);
        app.MapPost("/api/v1/scenario-proposals/{id:guid}/validate", async (Guid id, ClaimsPrincipal user, PlatformDbContext db, ScenarioBlueprintValidator validator, IAuthoringCapabilityCatalog catalogs, IScenarioRuleCompiler compiler, IScenarioBlueprintAdapterRegistry adapters, IClock clock, CancellationToken ct) => { var owner=Id(user); var row=await db.ScenarioProposals.SingleOrDefaultAsync(x=>x.Id==id&&x.OwnerInstructorUserId==owner,ct)??throw new DomainException("scenario_proposal.not_found","Proposal was not found."); var blueprint=JsonSerializer.Deserialize<ScenarioBlueprint>(row.CurrentBlueprintJson)!; var report=validator.Validate(blueprint); var blockers=report.Blockers.ToList(); if(adapters.TryResolve(blueprint.ModelIdentifier,blueprint.ModelVersion,out var adapter)){var catalog=catalogs.GetCatalog(blueprint.ModelIdentifier,blueprint.ModelVersion);var objectives=blueprint.LearningObjectives.Select(x=>x.Code).ToHashSet();var compiled=blueprint.Rules.Select(x=>compiler.Compile(x,catalog,objectives)).ToList();blockers.AddRange(compiled.SelectMany(x=>x.Blockers).Select(x=>new BlueprintIssue(x.Code,x.Message,$"rules/{x.RuleId}",x.Severity)));if(compiled.All(x=>x.IsValid)){var adapted=adapter.Adapt(blueprint,compiled.Select(x=>x.CompiledRule!).ToList());blockers.AddRange(adapted.Blockers.Select(x=>new BlueprintIssue(x.Code,x.Message,x.Path,x.Severity)));}}else blockers.Add(new BlueprintIssue("scenario_blueprint.adapter_not_found","No adapter exists for this model version.","modelVersion","Blocker")); var valid=blockers.Count==0; if(valid)row.Status="Validated";else row.Status="Draft"; db.ScenarioProposalValidations.Add(new ScenarioProposalValidationRow{Id=Guid.NewGuid(),ProposalId=id,RevisionNumber=row.CurrentRevisionNumber,ProposalVersion=row.Version,IsValid=valid,BlockersJson=JsonSerializer.Serialize(blockers),WarningsJson=JsonSerializer.Serialize(report.Warnings),ModelIdentifier=row.ModelIdentifier,ModelVersion=row.ModelVersion,ValidatedByUserId=owner,ValidatedAt=clock.UtcNow}); await db.SaveChangesAsync(ct); return Results.Ok(new ScenarioBlueprintValidationReport(valid,blockers,report.Warnings)); }).RequireAuthorization(PlatformPolicies.Instructor);
app.MapPost("/api/v1/scenario-proposals/{id:guid}/reject", async (Guid id, ProposalDecision request, ClaimsPrincipal user, IScenarioProposalRejectionService rejection, HttpContext http, CancellationToken ct) => { var key=http.Request.Headers["Idempotency-Key"].ToString(); if(string.IsNullOrWhiteSpace(key))throw new DomainException("idempotency.missing_key","Idempotency-Key is required."); var result=await rejection.RejectAsync(new ScenarioProposalRejectionCommand(id,Id(user),request.ExpectedVersion,key),ct); return Results.Content(result.ResponseBody,"application/json",System.Text.Encoding.UTF8,result.StatusCode); }).RequireAuthorization(PlatformPolicies.Instructor);
app.MapPost("/api/v1/scenario-proposals/{id:guid}/approve", async (Guid id, ProposalDecision request, ClaimsPrincipal user, IScenarioProposalApprovalService approval, HttpContext http, CancellationToken ct) => { var key=http.Request.Headers["Idempotency-Key"].ToString(); if(string.IsNullOrWhiteSpace(key))throw new DomainException("idempotency.missing_key","Idempotency-Key is required."); var result=await approval.ApproveAsync(new ScenarioProposalApprovalCommand(id,Id(user),request.ExpectedVersion,key),ct); return Results.Content(result.ResponseBody,"application/json",System.Text.Encoding.UTF8,result.StatusCode); }).RequireAuthorization(PlatformPolicies.Instructor);
    }
    private static Guid Id(ClaimsPrincipal p)=>Guid.Parse(p.FindFirstValue(ClaimTypes.NameIdentifier)??p.FindFirstValue("sub")!);
}
public sealed record ScenarioProposalUpdate(long ExpectedVersion, ScenarioBlueprint Blueprint, string? RevisionSource, string? Instruction);
public sealed record ProposalDecision(long ExpectedVersion);
